/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadHubRouteImport } from './routes/upload-hub'
import { Route as SimilarwebRouteImport } from './routes/similarweb'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonthMonthRouteImport } from './routes/month.$month'

const UploadHubRoute = UploadHubRouteImport.update({
  id: '/upload-hub',
  path: '/upload-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const SimilarwebRoute = SimilarwebRouteImport.update({
  id: '/similarweb',
  path: '/similarweb',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthMonthRoute = MonthMonthRouteImport.update({
  id: '/month/$month',
  path: '/month/$month',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reference': typeof ReferenceRoute
  '/similarweb': typeof SimilarwebRoute
  '/upload-hub': typeof UploadHubRoute
  '/month/$month': typeof MonthMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reference': typeof ReferenceRoute
  '/similarweb': typeof SimilarwebRoute
  '/upload-hub': typeof UploadHubRoute
  '/month/$month': typeof MonthMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reference': typeof ReferenceRoute
  '/similarweb': typeof SimilarwebRoute
  '/upload-hub': typeof UploadHubRoute
  '/month/$month': typeof MonthMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reference'
    | '/similarweb'
    | '/upload-hub'
    | '/month/$month'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reference' | '/similarweb' | '/upload-hub' | '/month/$month'
  id:
    | '__root__'
    | '/'
    | '/reference'
    | '/similarweb'
    | '/upload-hub'
    | '/month/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReferenceRoute: typeof ReferenceRoute
  SimilarwebRoute: typeof SimilarwebRoute
  UploadHubRoute: typeof UploadHubRoute
  MonthMonthRoute: typeof MonthMonthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-hub': {
      id: '/upload-hub'
      path: '/upload-hub'
      fullPath: '/upload-hub'
      preLoaderRoute: typeof UploadHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/similarweb': {
      id: '/similarweb'
      path: '/similarweb'
      fullPath: '/similarweb'
      preLoaderRoute: typeof SimilarwebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/month/$month': {
      id: '/month/$month'
      path: '/month/$month'
      fullPath: '/month/$month'
      preLoaderRoute: typeof MonthMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReferenceRoute: ReferenceRoute,
  SimilarwebRoute: SimilarwebRoute,
  UploadHubRoute: UploadHubRoute,
  MonthMonthRoute: MonthMonthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
